version: '27.3.1'

services:
  database:
    image: postgres
    container_name: banco_docker
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
  volumes:
    - pg:/data/postgres

  volumes:
    pgdata:
      driver: local